#!/bin/sh

. /usr/lib/rc/functions

config(){
    [ -d /run/tmpfiles.d ] || mkdir /run/tmpfiles.d
    kmod static-nodes --format=tmpfiles --output=/run/tmpfiles.d/kmod.conf
}

case "$1" in
    start)
        stat_busy "Starting kmod-static-nodes"
        config
        add_daemon kmod-static-nodes
        stat_done
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
