#!/bin/sh

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Starting mount-all"
        netfs_prefix_no
        mount -a -t "${NETFS}" -O no_netdev || stat_die mount-all
        add_daemon mount-all
        stat_done mount-all
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
