#!/bin/sh

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Starting net-lo"
        ip link set up dev lo || stat_die
        add_daemon net-lo
        stat_done
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
