#!/bin/sh

. /usr/lib/rc/functions

mount_procfs(){
    mountpoint -q /proc || mount -t proc proc /proc -o nosuid,noexec,nodev
}

case "$1" in
    start)
        stat_busy "Mounting proc filesystem"
        mount_procfs
        add_daemon procfs
        stat_done
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
