#!/bin/sh

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Loading sysctl settings"
        sysctl --system || stat_die sysctl
        add_daemon sysctl
        stat_done sysctl
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
