#!/bin/sh

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Starting sysusers"
        sysusers
        add_daemon sysusers
        stat_done
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
