#!/bin/sh

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Starting tmpfiles-dev"
        tmpfiles --prefix=/dev --create --boot || stat_die tmpfiles-dev
        add_daemon tmpfiles-dev
        stat_done tmpfiles-dev
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
