#!/bin/sh

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Starting tmpfiles-setup"
        tmpfiles --exclude-prefix=/dev --create --remove --boot || stat_die tmpfiles-setup
        add_daemon tmpfiles-setup
        stat_done tmpfiles-setup
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
