#!/bin/sh

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Triggering udev uevents"
        udevadm trigger --action=add --type=subsystems
        ret=$?
        udevadm trigger --action=add --type=devices
        math_check "$(( ret || $? ))" && stat_die udev-trigger
        add_daemon udev-trigger
        stat_done udev-trigger
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac

